### ISSUE TITLE
node_module missing src/main/tpl folder

### ISSUE THREAD

**Issue by sanjaybhatol** [qiwi/tech-radar#98]
## Issue type
* [ ] bug report

## Expected behavior
Node module @qiwishould have `tech-radar/src/main/tpl` folder.

## Actual behavior
node module @qiwi is missing `tech-radar/src/main/tpl` folder.

## Steps to reproduce
Run following command:
npx @qiwi/tech-radar --input "/path/to/files/*.{json, csv, yml}" --output radar

Following error is returned:
Error: ENOENT: no such file or directory, lstat '/Users/sanjay/Downloads/tech-radar-master/node_modules/@qiwi/tech-radar/src/main/tpl'

This stops from running the tech-radar locally. The dist generated static version works fine though. Only local build is failing due to this.

FYI,  dependency "@qiwi/tech-radar": "1.13.11" doesn't have this issue.

## Specifications
- version: Latest master branch

**Comment by antongolub** [comment]
@templates,

Nice catch, thanks!
